version: "3.1"
services:
  #  client:
  #    image: node:14-alpine
  #    environment:
  #      - CHOKIDAR_USEPOLLING=true
  #    ports:
  #      - "3000:3000"
  #    volumes:
  #      - ./client:/app
  #    working_dir: /app
  #    command: tail -f /dev/null
  #privileged: true
  mongo:
    image: mongo:4.2-bionic
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 20167
      MONGO_INITDB_ROOT_PASSWORD: 272065
      # MONGO_REPLICA_SET_NAME: rs0
    ports:
      - "0.0.0.0:27018:27017"
    volumes:
      - ./data/mongo:/data/db
    # command: ["--replSet", "rs0", "--bind_ip_all"]
  server:
    image: node:latest
    depends_on:
      - mongo
    # environment:
    # NODE_ENV: default
    ports:
      - "8083:8083"
    volumes:
      - ./Nooo:/Nooo
      - ./data/files:/app/files
      - ./server:/app
    working_dir: /app
    command: tail -f /dev/null
